### PR TITLE
1 unittest

### PR DESCRIPTION
**Pull request by MichaelChristenson**
This change is [Reviewable](https://reviewable.io/reviews/seaborngames/requestclient/3)

### CODE REVIEW

**Comment by christensonb** [comment]
These tests need to be made pep 8 with 80 columns, and properly formatted code

---

Reviewed 2 of 3 files at r2, 2 of 3 files at r3.
Review status: 4 of 5 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/requestclient/3#-:-L3Pr5U6XmsT77oA5yvO:b-2vafzp)*

**Comment by christensonb** [comment]
Reviewed 1 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/requestclient/3)*

**Comment by christensonb** [comment]
also remove the commented out smoke test

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/requestclient/3#-:-L3PrMnRcGII09ZZRcI9:b14r36k)*

**Comment by christensonb** [comment]
Reviewed 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[setup.py, line 30 at r4](https://reviewable.io:443/reviews/seaborngames/requestclient/3#-L4UBMy4XUGZnrD9aKQN:-L4UBMy4XUGZnrD9aKQO:b-qf80ro) ([raw file](https://github.com/seaborngames/requestclient/blob/71878e18a4863816387c1c5f822b98f454d01473/setup.py#L30)):*
> ```Python
>         'Natural Language :: English',
>         'License :: Other/Proprietary License',
>         'Operating System :: POSIX :: Linux :: Windows',
> ```

why are you removing windows

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/requestclient/3)*

**Comment by MichaelChristenson** [comment]
Reviewed 2 of 2 files at r6.
Review status: 9 of 17 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/seaborngames/requestclient/3)*

**Pull request closed without merging**
